# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39abeedf05af9442317eb836d77788c80999fa6a77ba6ad2b3d265958de9421b956b1722bf97294db987de4049a9e29bb424c73b47cb5f7f72a30e7508abfdb6

test:
  secret_key_base: 78ae1cc4865149011c936b6c4571c79fb560a52e4fb3846aca571e43f5d24b1a22dd1902fc265d2ce6bd5aee9267078a2084662889c2fb4919ab98c3fe482c6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
